//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingdomMapMod.TwoCrowns {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KingdomMapMod.TwoCrowns.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archer.
        /// </summary>
        internal static string Archer {
            get {
                return ResourceManager.GetString("Archer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barrier.
        /// </summary>
        internal static string Barrier {
            get {
                return ResourceManager.GetString("Barrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bear.
        /// </summary>
        internal static string Bear {
            get {
                return ResourceManager.GetString("Bear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BeggarCamp.
        /// </summary>
        internal static string BeggarCamp {
            get {
                return ResourceManager.GetString("BeggarCamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloodstained.
        /// </summary>
        internal static string Bloodstained {
            get {
                return ResourceManager.GetString("Bloodstained", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat.
        /// </summary>
        internal static string Boat {
            get {
                return ResourceManager.GetString("Boat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campfire.
        /// </summary>
        internal static string Campfire {
            get {
                return ResourceManager.GetString("Campfire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle.
        /// </summary>
        internal static string Castle {
            get {
                return ResourceManager.GetString("Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CatCart.
        /// </summary>
        internal static string CatCart {
            get {
                return ResourceManager.GetString("CatCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chest.
        /// </summary>
        internal static string Chest {
            get {
                return ResourceManager.GetString("Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliff.
        /// </summary>
        internal static string Cliff {
            get {
                return ResourceManager.GetString("Cliff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DayNight.
        /// </summary>
        internal static string DayNight {
            get {
                return ResourceManager.GetString("DayNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horse.
        /// </summary>
        internal static string DefaultSteed {
            get {
                return ResourceManager.GetString("DefaultSteed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        internal static string Dock {
            get {
                return ResourceManager.GetString("Dock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DogTree.
        /// </summary>
        internal static string DogSpawn {
            get {
                return ResourceManager.GetString("DogSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer.
        /// </summary>
        internal static string Farmer {
            get {
                return ResourceManager.GetString("Farmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmhouse.
        /// </summary>
        internal static string Farmhouse {
            get {
                return ResourceManager.GetString("Farmhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmlands.
        /// </summary>
        internal static string Farmlands {
            get {
                return ResourceManager.GetString("Farmlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GemChest.
        /// </summary>
        internal static string GemChest {
            get {
                return ResourceManager.GetString("GemChest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Griffin.
        /// </summary>
        internal static string Griffin {
            get {
                return ResourceManager.GetString("Griffin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gullinbursti.
        /// </summary>
        internal static string Gullinbursti {
            get {
                return ResourceManager.GetString("Gullinbursti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HermitBaker.
        /// </summary>
        internal static string HermitBaker {
            get {
                return ResourceManager.GetString("HermitBaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HermitBallista.
        /// </summary>
        internal static string HermitBallista {
            get {
                return ResourceManager.GetString("HermitBallista", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HermitHorn.
        /// </summary>
        internal static string HermitHorn {
            get {
                return ResourceManager.GetString("HermitHorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HermitHorse.
        /// </summary>
        internal static string HermitHorse {
            get {
                return ResourceManager.GetString("HermitHorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HermitKnight.
        /// </summary>
        internal static string HermitKnight {
            get {
                return ResourceManager.GetString("HermitKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HorseBurst.
        /// </summary>
        internal static string HorseBurst {
            get {
                return ResourceManager.GetString("HorseBurst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HorseFast.
        /// </summary>
        internal static string HorseFast {
            get {
                return ResourceManager.GetString("HorseFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HorseStamina.
        /// </summary>
        internal static string HorseStamina {
            get {
                return ResourceManager.GetString("HorseStamina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kelpie.
        /// </summary>
        internal static string Kelpie {
            get {
                return ResourceManager.GetString("Kelpie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lizard.
        /// </summary>
        internal static string Lizard {
            get {
                return ResourceManager.GetString("Lizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mine.
        /// </summary>
        internal static string Mine {
            get {
                return ResourceManager.GetString("Mine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peasant.
        /// </summary>
        internal static string Peasant {
            get {
                return ResourceManager.GetString("Peasant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portal.
        /// </summary>
        internal static string Portal {
            get {
                return ResourceManager.GetString("Portal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarry.
        /// </summary>
        internal static string Quarry {
            get {
                return ResourceManager.GetString("Quarry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reindeer.
        /// </summary>
        internal static string Reindeer {
            get {
                return ResourceManager.GetString("Reindeer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleipnir.
        /// </summary>
        internal static string Sleipnir {
            get {
                return ResourceManager.GetString("Sleipnir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spookyhorse.
        /// </summary>
        internal static string Spookyhorse {
            get {
                return ResourceManager.GetString("Spookyhorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stag.
        /// </summary>
        internal static string Stag {
            get {
                return ResourceManager.GetString("Stag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatueArcher.
        /// </summary>
        internal static string StatueArcher {
            get {
                return ResourceManager.GetString("StatueArcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatueFarmer.
        /// </summary>
        internal static string StatueFarmer {
            get {
                return ResourceManager.GetString("StatueFarmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatueKnight.
        /// </summary>
        internal static string StatueKnight {
            get {
                return ResourceManager.GetString("StatueKnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatueTime.
        /// </summary>
        internal static string StatueTime {
            get {
                return ResourceManager.GetString("StatueTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatueWorker.
        /// </summary>
        internal static string StatueWorker {
            get {
                return ResourceManager.GetString("StatueWorker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trap.
        /// </summary>
        internal static string Trap {
            get {
                return ResourceManager.GetString("Trap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unicorn.
        /// </summary>
        internal static string Unicorn {
            get {
                return ResourceManager.GetString("Unicorn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۩.
        /// </summary>
        internal static string Wall {
            get {
                return ResourceManager.GetString("Wall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ۩.
        /// </summary>
        internal static string WallWreck {
            get {
                return ResourceManager.GetString("WallWreck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warhorse.
        /// </summary>
        internal static string Warhorse {
            get {
                return ResourceManager.GetString("Warhorse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wolf.
        /// </summary>
        internal static string Wolf {
            get {
                return ResourceManager.GetString("Wolf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string Worker {
            get {
                return ResourceManager.GetString("Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wreck.
        /// </summary>
        internal static string Wreck {
            get {
                return ResourceManager.GetString("Wreck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string You {
            get {
                return ResourceManager.GetString("You", resourceCulture);
            }
        }
    }
}
